# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#hero'
    weight: 10
  - identifier : "Our Team1"
    name: "Emilio M. Bruna"
    url: "#about"
    parent: "Our Team"
    weight: 1
  - identifier: "Our Team2"
    name: "Current Lab Members"
    url: "#people"
    parent: "Our Team"
    weight: 2
  - identifier: "Our Team3"
    name: "Lab Alumni"
    url: "/lab-alumni/lab-alumni"
    parent: "Our Team"
    weight: 3
  - identifier: "Our Team4"
    name: "Join us"
    url: "/post/join-us"
    parent: "Our Team"
    weight: 4
  - name: Our Team
    url: '#about'
    weight: 20
  - name: Projects
    url: '#projects'
    weight: 30
  # - name: Talks
  #   url: '#talks'
  #   weight: 30
  # - identifier : "Publications1"
  #   name: "Recent Publications"
  #   url: "#publications"
  #   parent: "Publications"
  #   weight: 1
  # - identifier: "Publications2"
  #   name: "Complete List"
  #   url: "/publication/"
  #   parent: "Publications"
  #   weight: 2
  - name: Publications
    url: '#publications'
    weight: 40
  - name: Courses
    url: courses/
    weight: 50
  - name: Contact
    url: '#contact'
    weight: 60
  # - name: Posts
  #   url: '#posts'
  #   weight: 70
